name: Release

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_NAME: "rviews"
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC",
            artifact_ext: '.tar.gz',
            os: ubuntu-latest,
            cc: "gcc",
            cxx: "g++",
          }

    steps:
    
    - name: set version name
      id: version
      run: echo ::set-output name=name::${GITHUB_REF#refs/tags/}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.HOME }}/.local
        key: ${{ runner.os }}-dependencies

    - name: install GoogleTest
      if: ${{ steps.cache.output.cache-hit != 'true' }}
      run: |
        cd ..
        git clone https://github.com/google/googletest.git --branch release-1.10.0
        cd googletest
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX="$HOME/.local" -Dgtest_force_shared_crt=1
        cmake --build build --config Release
        cmake --build build --target install --config Release

    - name: run tests
      run: |
        rm -rf build/
        mkdir build
        cd build && cmake .. -DCMAKE_INSTALL_PREFIX="$HOME/.local" -Drviews_ENABLE_UNIT_TESTING=1
        cd ../ && cmake --build build --config Release
        cd build/test && ctest -C Release -VV

    # for a release not containing directly the source code, replace the files archived
    # with the actual files needed (i.e. *.lib/*.a and *.h(pp))

    - name: generate archive
      run: |
        tar -cvzf $HOME/artifact.tar.gz .

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-${{ steps.version.outputs.name }}
        path: '~/artifact.*'

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: set version name
      id: version
      run: echo ::set-output name=name::${GITHUB_REF#refs/tags/}

    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version.outputs.name }}
        # if needed, you can set the release body here
        #body: "Release notes"
        draft: false
        prerelease: false

    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: "Linux-${{ steps.version.outputs.name }}"
        path: ./

    - name: upload ubuntu release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "artifact.tar.gz"
        asset_name: "${{ env.PROJECT_NAME }}-Linux-${{ steps.version.outputs.name }}.tar.gz"
        asset_content_type: application/x-tar
